name = "neis-helper"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./out"

[[d1_databases]]
binding = "DB"
database_name = "neis-helper-db"
database_id = "9e1252c6-c9d5-40cb-95c6-db3505e4eecf"
